<?php
/**
 * Appfuel
 * Copyright (c) Robert Scott-Buccleuch <rsb.appfuel@gmail.com>
 * See LICENSE file at project root for details.
 */
return array(
    '\Appfuel\App\AppPathInterface'                     => 'Appfuel/App/AppPathInterface.php',
    '\Appfuel\App\AppPath'                              => 'Appfuel/App/AppPath.php',
    '\Appfuel\App\AppHandlerInterface'                  => 'Appfuel/App/AppHandlerInterface.php',
    '\Appfuel\App\AppHandler'                           => 'Appfuel/App/AppHandler.php',
    '\Appfuel\App\ConsoleHandlerInterface'              => 'Appfuel/App/ConsoleHandlerInterface.php',
    '\Appfuel\App\ConsoleHandler'                       => 'Appfuel/App/ConsoleHandler.php',
    '\Appfuel\App\WebHandlerInterface'                  => 'Appfuel/App/WebHandlerInterface.php',
    '\Appfuel\App\WebHandler'                           => 'Appfuel/App/WebHandler.php',
    '\Appfuel\App\ConfigHandlerInterface'               => 'Appfuel/App/ConfigHandlerInterface.php',
    '\Appfuel\App\ConfigHandler'                        => 'Appfuel/App/ConfigHandler.php',
    '\Appfuel\App\AppFactoryInterface'                  => 'Appfuel/App/AppFactoryInterface.php',
    '\Appfuel\App\AppFactory'                           => 'Appfuel/App/AppFactory.php',
    '\Appfuel\App\AppRegistry'                          => 'Appfuel/App/AppRegistry.php',
    '\Appfuel\Error\PHPErrorLevelInterface'             => 'Appfuel/Error/PHPErrorLevelInterface.php',
    '\Appfuel\Error\PHPErrorLevel'                      => 'Appfuel/Error/PHPErrorLevel.php',
    '\Appfuel\Error\ErrorInterface'                     => 'Appfuel/Error/ErrorInterface.php',
    '\Appfuel\Error\ErrorStackInterface'                => 'Appfuel/Error/ErrorStackInterface.php',
    '\Appfuel\Error\ErrorItem'                          => 'Appfuel/Error/ErrorItem.php',
    '\Appfuel\Error\ErrorStack'                         => 'Appfuel/Error/ErrorStack.php',
    '\Appfuel\Filesystem\FileFinderInterface'           => 'Appfuel/Filesystem/FileFinderInterface.php',
    '\Appfuel\Filesystem\FileReaderInterface'           => 'Appfuel/Filesystem/FileReaderInterface.php',
    '\Appfuel\Filesystem\FileWriterInterface'           => 'Appfuel/Filesystem/FileWriterInterface.php',
    '\Appfuel\Filesystem\FileFinder'                    => 'Appfuel/Filesystem/FileFinder.php',
    '\Appfuel\Filesystem\FileReader'                    => 'Appfuel/Filesystem/FileReader.php',
    '\Appfuel\Filesystem\FileWriter'                    => 'Appfuel/Filesystem/FileWriter.php',
    '\Appfuel\DataStructure\ArrayDataInterface'         => 'Appfuel/DataStructure/ArrayDataInterface.php',
    '\Appfuel\DataStructure\ArrayData'                  => 'Appfuel/DataStructure/ArrayData.php',
    '\Appfuel\Console\ConsoleOutputInterface'           => 'Appfuel/Console/ConsoleOutputInterface.php',
    '\Appfuel\Console\ConsoleOutput'                    => 'Appfuel/Console/ConsoleOutput.php',
    '\Appfuel\Http\HttpOutputInterface'                 => 'Appfuel/Http/HttpOutputInterface.php',
    '\Appfuel\Http\HttpOutput'                          => 'Appfuel/Http/HttpOutput.php',
    '\Appfuel\Kernel\FaultHandlerInterface'             => 'Appfuel/Kernel/FaultHandlerInterface.php',
    '\Appfuel\ClassLoader\AutoLoaderInterface'          => 'Appfuel/ClassLoader/AutoLoaderInterface.php',
    '\Appfuel\ClassLoader\StandardAutoLoader'           => 'Appfuel/ClassLoader/StandardAutoLoader.php',
    '\Appfuel\ClassLoader\NamespaceParserInterface'     => 'Appfuel/ClassLoader/NamespaceParserInterface.php',
    '\Appfuel\ClassLoader\NamespaceParser'              => 'Appfuel/ClassLoader/NamespaceParser.php',
    '\Appfuel\Kernel\FaultHandlerInterface'             => 'Appfuel/Kernel/FaultHandlerInterface.php',
    '\Appfuel\Kernel\FaultHandler'                      => 'Appfuel/Kernel/FaultHandler.php',
    '\Appfuel\Kernel\Task\TaskHandlerInterface'         => 'Appfuel/Kernel/Task/TaskHandlerInterface.php',
    '\Appfuel\Kernel\Task\TaskHandler'                  => 'Appfuel/Kernel/Task/TaskHandler.php',
    '\Appfuel\Kernel\Task\StartupTaskInterface'         => 'Appfuel/Kernel/Task/StartupTaskInterface.php',
    '\Appfuel\Kernel\Task\StartupTask'                  => 'Appfuel/Kernel/Task/StartupTask.php',
    '\Appfuel\Kerenl\Task\PHPIniTask'                   => 'Appfuel/Kernel/Task/PHPIniTask.php',
    '\Appfuel\Kerenl\Task\PHPErrorTask'                 => 'Appfuel/Kernel/Task/PHPErrorTask.php',
    '\Appfuel\Kernel\Task\PHPPathTask'                  => 'Appfuel/Kernel/Task/PHPPathTask.php',
    '\Appfuel\Kernel\Task\FaultHandlerTask'             => 'Appfuel/Kernel/Task/FaultHandlerTask.php',
    '\Appfuel\Kernel\Task\PHPAutoloaderTask'            => 'Appfuel/Kernel/Task/PHPAutoloaderTask.php',
    '\Appfuel\Kernel\Task\PHPDefaultTimezoneTask'       => 'Appfuel/Kernel/Task/PHPDefaultTimezoneTask.php',    
    '\Appfuel\Kernel\Task\DependencyLoaderTask'         => 'Appfuel/Kernel/Task/DependencyLoaderTask.php',
    '\Appfuel\Validate\ValidationStartupTask'           => 'Appfuel/Validate/ValidationStartupTask.php',
    '\Appfuel\Log\LogPriorityInterface'                 => 'Appfuel/Log/LogPriorityInterface.php',
    '\Appfuel\Log\LogEntryInterface'                    => 'Appfuel/Log/LogEntryInterface.php',
    '\Appfuel\Log\LogAdapterInterface'                  => 'Appfuel/Log/LogAdapterInterface.php',
    '\Appfuel\Log\LoggerInterface'                      => 'Appfuel/Log/LoggerInterface.php',
    '\Appfuel\Log\SysLogAdapter'                        => 'Appfuel/Log/SysLogAdapter.php',
    '\Appfuel\Log\LogEntry'                             => 'Appfuel/Log/LogEntry.php',
    '\Appfuel\Log\LogPriority'                          => 'Appfuel/Log/LogPriority.php',
    '\Appfuel\Log\Logger'                               => 'Appfuel/Log/Logger.php'
);
